version: '3.1'
services:
  db:
    image: postgres:15.3-alpine3.18
    environment:
      POSTGRES_USER: pgc2
      POSTGRES_DB: pgc2
      POSTGRES_PASSWORD: M5LzSQNyWlIz7icbKxSAlgGkVwS9rUJc
    healthcheck:
      test: 'pg_isready --username=$$POSTGRES_USER && psql --username=$$POSTGRES_USER --list'
      interval: 5s
      timeout: 10s
      retries: 20
    ports:
      - 127.0.0.1:5432:5432

  server:
    build:
      context: .
      dockerfile: docker/server/Dockerfile
    restart: on-failure
    depends_on:
      db:
        condition: service_started
    environment:
      SQLALCHEMY_DATABASE_URI: 'postgresql+psycopg://pgc2:M5LzSQNyWlIz7icbKxSAlgGkVwS9rUJc@db/pgc2'
      INITIAL_USERS: '[{"username": "worker", "password": "B4kuKY8AV4oCQWQy8G1fer7Hlpp75hpS"}]'

  worker:
    build:
      context: .
      dockerfile: docker/worker/Dockerfile
    restart: on-failure
    depends_on:
      db:
        condition: service_started
    environment:
      SQLALCHEMY_DATABASE_URI: 'postgresql+psycopg://worker:B4kuKY8AV4oCQWQy8G1fer7Hlpp75hpS@db/pgc2'
